### ISSUE TITLE
使用nvm启动，报错

### ISSUE THREAD

**Issue by 2lei** [chungchi300/koa2-safe-start#1]
![image](https://user-images.githubusercontent.com/12872293/35492819-229220f2-04ea-11e8-8944-82cef9401dd5.png)
``` javascript
node src/app.js
```
可以正常工作

**Comment by klren0312** [comment]
```
npm install -g nodemon
```
然后把`$(npm bin)\`删了 即可

**Comment by chungchi300** [comment]
我只在Linux测试了它，在Windows上这个问题确实存在

@klren0312 
一个可行的和临时的解决方案

**Comment by chungchi300** [comment]
已经解决:

https://github.com/chungchi300/koa2-safe-start/commit/332ab3ef62439b6bc67d94b6a24b290fcf557df2
